=== sassoftware/xml_resources/xsd/rpath-configurator-1.0.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="rPathConfigurator" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">

  <!-- rPath configuration top level elements -->
  <xs:element name="validation_report" type="ConfigValidationReport"></xs:element>
  
  <!-- Validation report complex type -->
  <xs:complexType name="ConfigValidationReport">
    <xs:sequence>
        <xs:element name="name" type="xs:Name" maxOccurs="1"
            minOccurs="1">
        </xs:element>
        <xs:element name="message" type="xs:string" maxOccurs="1"
            minOccurs="1">
        </xs:element>
        <xs:element name="details" type="xs:string" maxOccurs="1"
            minOccurs="1">
        </xs:element>
        <xs:element name="errors" type="ConfigErrors" maxOccurs="1"
            minOccurs="0">
        </xs:element>
        <xs:element name="checks" type="ConfigChecks" maxOccurs="1"
            minOccurs="1">
        </xs:element>
        <xs:element name="success" type="xs:boolean" maxOccurs="1" minOccurs="0"></xs:element>
    </xs:sequence>
    <xs:attribute name="version" type="xs:string"></xs:attribute>
  </xs:complexType>

  <!--  Generic complex types -->

  <xs:complexType name="ConfigError">
  	<xs:sequence>
  		<xs:element name="code" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
  		<xs:element name="detail" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
  		<xs:element name="message" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
  	</xs:sequence>
  </xs:complexType>

  <xs:complexType name="ConfigErrors">
  	<xs:sequence>
  		<xs:element name="error" type="ConfigError" maxOccurs="unbounded" minOccurs="1"></xs:element>
  	</xs:sequence>
  </xs:complexType>

  <xs:complexType name="ConfigCheck">
  	<xs:sequence>
  		<xs:element name="name" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
  		<xs:element name="message" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
  		<xs:element name="success" type="xs:boolean" maxOccurs="1" minOccurs="1"></xs:element>
  	</xs:sequence>
  </xs:complexType>

  <xs:complexType name="ConfigChecks">
  	<xs:sequence>
  		<xs:element name="probe" type="ConfigCheck" maxOccurs="unbounded" minOccurs="1"></xs:element>
  	</xs:sequence>
  </xs:complexType>

</xs:schema>

=== sassoftware/xml_resources/xsd/customer_validator_sample.xml
<validation_report version="2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.rpath.com/permanent/rpath-configurator-1.0.xsd rpath-configurator-1.0.xsd">
    <name>apache_configuration</name>
    <details>Result report details</details>
    <message>Result report message</message>
    <errors>
        <error>
            <code>500</code>
            <detail>Apache not started</detail>
            <message>General error: apache not running</message>
        </error>
        <error>
            <code>1</code>
            <detail>Traceback: A bunch of tb data</detail>
            <message>Error when stuff broke, fix it</message>
        </error>
    </errors>
    <checks>
        <check>
            <message>Apache not running on port</message>
            <name>Apache Port Check</name>
            <success>False</success>
        </check>
        <check>
            <message>Apache debug 5</message>
            <name>Apache Debug Check</name>
            <success>True</success>
        </check>
    </checks>
    <success>False</success> <!--  optional override -->
</validation_report>

=== sassoftware/xml_resources/samples/customer_xml/validate3.xml
<validation_report version="2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.rpath.com/permanent/rpath-configurator-1.0.xsd rpath-configurator-1.0.xsd">
    <name>tomcat_configuration</name>
    <message>tomcat result report message</message>
    <details>tomcat result report details</details>
    <errors>
        <error>
            <code>-1</code>
            <detail>File tomcat_checker not found</detail>
            <message>File tomcat_checker not found</message>
        </error>
    </errors>
</validation_report>

=== sassoftware/xml_resources/samples/customer_xml/validate1.xml
<validation_report version="2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.rpath.com/permanent/rpath-configurator-1.0.xsd rpath-configurator-1.0.xsd">
    <name>apache_configuration</name>
    <message>Result report message</message>
    <details>Result report details</details>
    <success>true</success>
    <errors>
        <error>
            <code>500</code>
            <detail>Apache not started</detail>
            <message>General error: apache not running</message>
        </error>
        <error>
            <code>1</code>
            <detail>Traceback: A bunch of tb data</detail>
            <message>Error when stuff broke, fix it</message>
        </error>
    </errors>
    <checks>
        <check>
            <message>Apache not running on port</message>
            <display_name>Apache Port Check</display_name>
            <name>port_check</name>
            <success>false</success>
        </check>
        <check>
            <message>Apache debug 5</message>
            <display_name>Apache Debug Check</display_name>
            <name>debug_check</name>
            <success>true</success>
        </check>
    </checks>
</validation_report>
