=== sassoftware/xml_resources/xsd/rpath-configurator-2.0.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="rPathConfigurator" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- rPath configuration top level elements -->
  <xs:element name="validation_report" type="ConfigValidationReport"></xs:element>
  <xs:element name="discovery_report" type="ConfigDiscoveryReport"></xs:element>
  <xs:element name="read_report" type="ConfigReadReport"></xs:element>

  <!-- Validation report complex type -->
  <xs:complexType name="ConfigValidationReport">
    <xs:all>
      <xs:element name="name" type="xs:Name" maxOccurs="1" minOccurs="1"></xs:element>
      <xs:element name="display_name" type="xs:normalizedString" maxOccurs="1" minOccurs="1"></xs:element>
      <xs:element name="summary" type="xs:normalizedString" maxOccurs="1" minOccurs="1"></xs:element>
      <xs:element name="details" type="xs:string" maxOccurs="1" minOccurs="0"></xs:element>      
      <xs:element name="success" type="xs:boolean" maxOccurs="1" minOccurs="1"></xs:element>   
      <xs:element name="errors" type="ConfigErrors" maxOccurs="1" minOccurs="0"></xs:element>
      <xs:element name="checks" type="ConfigChecks" maxOccurs="1" minOccurs="0"></xs:element>
    </xs:all>   
    <xs:attribute name="version" type="Version" use="required"></xs:attribute>
  </xs:complexType>

  <!-- Discovery report complex type -->
  <xs:complexType name="ConfigDiscoveryReport">
    <xs:all>
      <xs:element name="name" type="xs:Name" maxOccurs="1" minOccurs="1"></xs:element>
      <xs:element name="display_name" type="xs:normalizedString" maxOccurs="1" minOccurs="1"></xs:element>
      <xs:element name="errors" type="ConfigErrors" maxOccurs="1" minOccurs="0"></xs:element>
      <xs:element name="result" type="xs:string" maxOccurs="1" minOccurs="0"></xs:element>
    </xs:all>    
    <xs:attribute name="version" type="Version" use="required"></xs:attribute>
  </xs:complexType>
  
  <!-- Read report complex type -->
  <xs:complexType name="ConfigReadReport">
    <xs:all>
      <xs:element name="name" type="xs:Name" maxOccurs="1" minOccurs="1"></xs:element>
      <xs:element name="errors" type="ConfigErrors" maxOccurs="1" minOccurs="0"></xs:element>
      <xs:element name="properties" type="ConfigProperties" maxOccurs="1" minOccurs="0"></xs:element>
    </xs:all>    
    <xs:attribute name="version" type="Version" use="required"></xs:attribute>
  </xs:complexType>

  <!--  Generic complex types -->

  <xs:complexType name="ConfigError">
  	<xs:all>
  		<xs:element name="code" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
  		<xs:element name="details" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
  		<xs:element name="summary" type="xs:normalizedString" maxOccurs="1" minOccurs="1"></xs:element>
  	</xs:all>
  </xs:complexType>

  <xs:complexType name="ConfigErrors">
  	<xs:sequence>
  		<xs:element name="error" type="ConfigError" maxOccurs="unbounded" minOccurs="0"></xs:element>
  	</xs:sequence>
  </xs:complexType>

  <xs:complexType name="ConfigCheck">
  	<xs:all>
  		<xs:element name="name" type="xs:Name" maxOccurs="1" minOccurs="1"></xs:element>
  		<xs:element name="display_name" type="xs:normalizedString" maxOccurs="1" minOccurs="1"></xs:element>
  		<xs:element name="summary" type="xs:normalizedString" maxOccurs="1" minOccurs="1"></xs:element>
  		<xs:element name="details" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
  		<xs:element name="success" type="xs:boolean" maxOccurs="1" minOccurs="1"></xs:element>
  	</xs:all>
  </xs:complexType>

  <xs:complexType name="ConfigChecks">
  	<xs:sequence>
  		<xs:element name="check" type="ConfigCheck" maxOccurs="unbounded" minOccurs="0"></xs:element>
  	</xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="ConfigProperty">
    <xs:all>
      <xs:element name="name" type="xs:Name" maxOccurs="1" minOccurs="1"></xs:element>
      <xs:element name="value" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="ConfigProperties">
    <xs:sequence>
      <xs:element name="property" type="ConfigProperty" maxOccurs="unbounded" minOccurs="0"></xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:simpleType name="Version">
    <xs:restriction base="xs:decimal">
      <xs:enumeration value="2"/>
      <xs:enumeration value="2.0"/>
    </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== sassoftware/xml_resources/samples/customer_xml/read1.xml
<read_report version="2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.rpath.com/permanent/rpath-configurator-2.0.xsd rpath-configurator-2.0.xsd">
    <name>apache_configuration</name>
    <errors>
        <error>
            <code>500</code>
            <details><![CDATA[Apache not started]]></details>
            <summary>General error: apache not running</summary>
        </error>
        <error>
            <code>1</code>
            <details><![CDATA[Traceback: A bunch of tb data]]></details>
            <summary>Error when stuff broke, fix it</summary>
        </error>
    </errors>
    <properties>
        <property>
            <name>port</name>
            <value>81</value>
        </property>
        <property>
            <name>debug_level</name>
            <value>true</value>
        </property>
    </properties>
</read_report>
